#!/usr/bin/env python3
"""Turn unified_report.json into docs/data.js, appending this run to history."""
import json, os, re, sys
from datetime import datetime, timezone

report = json.load(open(sys.argv[1]))          # unified_report.json
data_js = sys.argv[2]                            # docs/data.js

# --- read existing history out of the current data.js (if any) ---
history = []
if os.path.exists(data_js):
    txt = open(data_js).read()
    m = re.search(r"window\.FIRMWARE_HISTORY\s*=\s*(\[.*?\]);", txt, re.S)
    if m:
        try: history = json.loads(m.group(1))
        except Exception: history = []

# --- append this run (dedupe by commit so re-runs don't double-count) ---
s = report.get("summary", {})
entry = {"date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
         "commit": report.get("commit", "")[:7],
         "total": s.get("total", 0), "high": s.get("high", 0),
         "medium": s.get("medium", 0), "info": s.get("info", 0)}
history = [h for h in history if h.get("commit") != entry["commit"]]
history.append(entry)
history = history[-30:]                           # keep last 30 runs

with open(data_js, "w") as f:
    f.write("// Auto-generated by the pipeline. Do not edit by hand.\n")
    f.write("window.FIRMWARE_LATEST = " + json.dumps(report, indent=2) + ";\n\n")
    f.write("window.FIRMWARE_HISTORY = " + json.dumps(history, indent=2) + ";\n")
print(f"[+] Dashboard data written: {len(report.get('findings', []))} findings, {len(history)} history points")